spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  session:
    store-type: redis

logging:
  level:
    root: info