name: Backend CD
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v3
        
      - name: JDK 11을 설치합니다.
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 빌드를 위한 권한 부여 # (1)
        run: chmod +x gradlew
        
      - name: Build and analyze
        run: ./gradlew clean build

      - name: 도커 이미지 빌드 # (2)
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/unknown-server .

      - name: Docker Hub 로그인 # (3)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub 퍼블리시 # (4)
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/unknown-server
